package contextengine

import "errors"

var (
	ErrInvalidWorkspaceID = errors.New("invalid workspace ID")
	ErrInvalidSourceID    = errors.New("invalid context source ID")
	ErrInvalidAnalyzerID  = errors.New("invalid context analyzer ID")
	ErrInvalidEstimatorID = errors.New("invalid token estimator ID")
	ErrInvalidPath        = errors.New("invalid document path")
	ErrInvalidDigest      = errors.New("invalid content digest")
	ErrInvalidPolicy      = errors.New("invalid workspace scan policy")
	ErrInvalidWorkspace   = errors.New("invalid workspace")
	ErrInvalidDocument    = errors.New("invalid context document")
	ErrInvalidRange       = errors.New("invalid source range")
	ErrInvalidDiagnostic  = errors.New("invalid context diagnostic")
	ErrInvalidAnalysis    = errors.New("invalid document analysis")
	ErrInvalidSnapshot    = errors.New("invalid context snapshot")
	ErrInvalidQuery       = errors.New("invalid retrieval query")
	ErrInvalidResult      = errors.New("invalid retrieval result")
	ErrInvalidBudget      = errors.New("invalid context budget")
	ErrInvalidSection     = errors.New("invalid context section")
	ErrInvalidBundle      = errors.New("invalid context bundle")
	ErrInvalidSource      = errors.New("invalid context source")
	ErrInvalidAnalyzer    = errors.New("invalid context analyzer")
	ErrInvalidEstimator   = errors.New("invalid token estimator")
	ErrAlreadyRegistered  = errors.New("context extension already registered")
	ErrNotFound           = errors.New("context resource not found")
	ErrAmbiguous          = errors.New("ambiguous context extension")
	ErrUnsupported        = errors.New("context operation unsupported")
	ErrLimitExceeded      = errors.New("context limit exceeded")
	ErrSourceFailure      = errors.New("context source failure")
	ErrAnalyzerFailure    = errors.New("context analyzer failure")
	ErrEstimatorFailure   = errors.New("token estimator failure")
	ErrEmbeddingFailure   = errors.New("context embedding failure")
	ErrBudgetExceeded     = errors.New("context budget exceeded")
)
